"""ledger: purchases, sales, adjustments, allocations, audit

Revision ID: 0002_ledger
Revises: 0001_foundation
Create Date: 2026-07-27 23:00:12.732200
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_ledger"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("action IN ('create', 'update', 'void')", name="ck_audit_action"),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_entity", "audit_log", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "inventory_adjustments",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=24), nullable=False),
        sa.Column("landed_cost_cents", sa.BigInteger(), nullable=True),
        sa.Column("adjustment_date", sa.Date(), nullable=True),
        sa.Column("member_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_member_id", sa.Uuid(), nullable=True),
        sa.Column("cost_removed_cents", sa.BigInteger(), nullable=True),
        sa.Column("has_unknown_cost", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('opening_inventory', 'correction', 'damaged', 'missing', 'opened', "
            "'given_away', 'personal_use', 'returned', 'written_off', 'other')",
            name="ck_adjustments_reason",
        ),
        sa.CheckConstraint("status IN ('active', 'voided')", name="ck_adjustments_status"),
        sa.CheckConstraint(
            "landed_cost_cents IS NULL OR landed_cost_cents >= 0",
            name="ck_adjustments_cost_non_negative",
        ),
        sa.CheckConstraint("quantity_delta <> 0", name="ck_adjustments_delta_non_zero"),
        sa.CheckConstraint(
            "quantity_delta > 0 OR landed_cost_cents IS NULL",
            name="ck_adjustments_cost_only_on_additions",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_adjustments_product_status",
        "inventory_adjustments",
        ["product_id", "status"],
        unique=False,
    )
    op.create_table(
        "purchases",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("gross_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("shipping_cents", sa.BigInteger(), nullable=False),
        sa.Column("tax_cents", sa.BigInteger(), nullable=False),
        sa.Column("fees_cents", sa.BigInteger(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=160), nullable=True),
        sa.Column("purchased_by_member_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_member_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'voided')", name="ck_purchases_status"),
        sa.CheckConstraint("fees_cents >= 0", name="ck_purchases_fees_non_negative"),
        sa.CheckConstraint("gross_amount_cents >= 0", name="ck_purchases_gross_non_negative"),
        sa.CheckConstraint("quantity > 0", name="ck_purchases_quantity_positive"),
        sa.CheckConstraint("shipping_cents >= 0", name="ck_purchases_shipping_non_negative"),
        sa.CheckConstraint("tax_cents >= 0", name="ck_purchases_tax_non_negative"),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchased_by_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_purchases_product_status", "purchases", ["product_id", "status"], unique=False
    )
    op.create_table(
        "sales",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("gross_amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("platform_fees_cents", sa.BigInteger(), nullable=False),
        sa.Column("payment_fees_cents", sa.BigInteger(), nullable=False),
        sa.Column("shipping_paid_cents", sa.BigInteger(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("marketplace", sa.String(length=120), nullable=True),
        sa.Column("sold_by_member_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_member_id", sa.Uuid(), nullable=True),
        sa.Column("cost_basis_cents", sa.BigInteger(), nullable=True),
        sa.Column("has_unknown_cost", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'voided')", name="ck_sales_status"),
        sa.CheckConstraint("gross_amount_cents >= 0", name="ck_sales_gross_non_negative"),
        sa.CheckConstraint("payment_fees_cents >= 0", name="ck_sales_payment_fees_non_negative"),
        sa.CheckConstraint("platform_fees_cents >= 0", name="ck_sales_platform_fees_non_negative"),
        sa.CheckConstraint("quantity > 0", name="ck_sales_quantity_positive"),
        sa.CheckConstraint("shipping_paid_cents >= 0", name="ck_sales_shipping_non_negative"),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sold_by_member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sales_product_status", "sales", ["product_id", "status"], unique=False)
    op.create_table(
        "cost_allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("purchase_id", sa.Uuid(), nullable=True),
        sa.Column("adjustment_supply_id", sa.Uuid(), nullable=True),
        sa.Column("sale_id", sa.Uuid(), nullable=True),
        sa.Column("adjustment_consumer_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("cost_cents", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "(purchase_id IS NOT NULL)::int + (adjustment_supply_id IS NOT NULL)::int <= 1",
            name="ck_allocations_at_most_one_supply",
        ),
        sa.CheckConstraint(
            "(sale_id IS NOT NULL)::int + (adjustment_consumer_id IS NOT NULL)::int = 1",
            name="ck_allocations_one_consumer",
        ),
        sa.CheckConstraint(
            "cost_cents IS NULL OR cost_cents >= 0", name="ck_allocations_cost_non_negative"
        ),
        sa.CheckConstraint(
            "purchase_id IS NOT NULL OR adjustment_supply_id IS NOT NULL OR cost_cents IS NULL",
            name="ck_allocations_shortfall_has_no_cost",
        ),
        sa.CheckConstraint("quantity > 0", name="ck_allocations_quantity_positive"),
        sa.ForeignKeyConstraint(
            ["adjustment_consumer_id"],
            ["inventory_adjustments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["adjustment_supply_id"],
            ["inventory_adjustments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_allocations_product", "cost_allocations", ["product_id"], unique=False)
    op.create_index("ix_allocations_sale", "cost_allocations", ["sale_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_allocations_sale", table_name="cost_allocations")
    op.drop_index("ix_allocations_product", table_name="cost_allocations")
    op.drop_table("cost_allocations")
    op.drop_index("ix_sales_product_status", table_name="sales")
    op.drop_table("sales")
    op.drop_index("ix_purchases_product_status", table_name="purchases")
    op.drop_table("purchases")
    op.drop_index("ix_adjustments_product_status", table_name="inventory_adjustments")
    op.drop_table("inventory_adjustments")
    op.drop_index("ix_audit_entity", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
